using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lua.SourceGenerator;

partial class LuaObjectGenerator
{
    /// <summary>
    /// Checks whether <paramref name="typeSymbol"/> has the <see cref="Lua.LuaObjectAttribute"/>.
    /// This is needed because source-generated implicit conversions and interface
    /// implementations may not exist in the compilation yet at the point the
    /// generator runs.
    /// </summary>
    static bool HasLuaObjectAttribute(ITypeSymbol typeSymbol, SymbolReferences references)
    {
        return typeSymbol is INamedTypeSymbol namedType
            && namedType.GetAttributes().Any(attr =>
                SymbolEqualityComparer.Default.Equals(
                    attr.AttributeClass, references.LuaObjectAttribute));
    }

    static string GetLuaValuePrefix(
        ITypeSymbol typeSymbol,
        SymbolReferences references,
        Compilation compilation
    )
    {
        if (SymbolEqualityComparer.Default.Equals(typeSymbol, references.Object))
        {
            return "global::Lua.LuaValue.FromObject(";
        }

        return compilation.ClassifyCommonConversion(typeSymbol, references.LuaUserData).Exists
            || HasLuaObjectAttribute(typeSymbol, references)
            ? "global::Lua.LuaValue.FromUserData("
            : "(";
    }

    static string GetLuaValueExpression(
        string expression,
        ITypeSymbol typeSymbol,
        SymbolReferences references,
        Compilation compilation
    )
    {
        return $"{GetLuaValuePrefix(typeSymbol, references, compilation)}{expression})";
    }

    static bool TryEmit(
        TypeMetadata typeMetadata,
        CodeBuilder builder,
        SymbolReferences references,
        Compilation compilation,
        in SourceProductionContext context,
        Dictionary<INamedTypeSymbol, TypeMetadata> metaDict,
        TempCollections tempCollections
    )
    {
        try
        {
            var error = false;

            // must be partial
            if (!typeMetadata.IsPartial())
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        DiagnosticDescriptors.MustBePartial,
                        typeMetadata.Syntax.Identifier.GetLocation(),
                        typeMetadata.Symbol.Name
                    )
                );
                error = true;
            }

            // nested is not allowed
            if (typeMetadata.IsNested())
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        DiagnosticDescriptors.NestedNotAllowed,
                        typeMetadata.Syntax.Identifier.GetLocation(),
                        typeMetadata.Symbol.Name
                    )
                );
                error = true;
            }

            if (!ValidateMembers(typeMetadata, compilation, references, context, metaDict))
            {
                error = true;
            }

            if (error)
            {
                return false;
            }

            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("#pragma warning disable CS0162 // Unreachable code");
            builder.AppendLine(
                "#pragma warning disable CS0219 // Variable assigned but never used"
            );
            builder.AppendLine(
                "#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type."
            );
            builder.AppendLine(
                "#pragma warning disable CS8601 // Possible null reference assignment"
            );
            builder.AppendLine("#pragma warning disable CS8602 // Possible null return");
            builder.AppendLine(
                "#pragma warning disable CS8604 // Possible null reference argument for parameter"
            );
            builder.AppendLine(
                "#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method"
            );
            builder.AppendLine();

            var ns = typeMetadata.Symbol.ContainingNamespace;
            if (!ns.IsGlobalNamespace)
            {
                builder.AppendLine($"namespace {ns}");
                builder.BeginBlock();
            }

            var isInterface = typeMetadata.Symbol.TypeKind == TypeKind.Interface;
            var typeDeclarationKeyword = isInterface
                ? "interface"
                : (
                    typeMetadata.Symbol.IsRecord,
                    typeMetadata.Symbol.IsValueType
                ) switch
                {
                    (true, true) => "record struct",
                    (true, false) => "record",
                    (false, true) => "struct",
                    (false, false) => "class",
                };

            using var _ = builder.BeginBlockScope(
                $"partial {typeDeclarationKeyword} {typeMetadata.TypeName} : global::Lua.ILuaUserData"
            );

            builder.AppendLine("private static class __Cache");
            builder.AppendLine("{");

            var metamethodSet = tempCollections.Metamethods;

            if (
                !TryEmitMethods(
                    typeMetadata,
                    builder,
                    references,
                    compilation,
                    metamethodSet,
                    tempCollections,
                    context
                )
            )
            {
                return false;
            }

            if (
                !TryEmitIndexMetamethod(
                    typeMetadata,
                    builder,
                    references,
                    compilation,
                    context,
                    tempCollections
                )
            )
            {
                return false;
            }

            metamethodSet.Add(LuaObjectMetamethod.Index);

            if (
                !TryEmitNewIndexMetamethod(
                    typeMetadata,
                    builder,
                    references,
                    compilation,
                    context,
                    tempCollections
                )
            )
            {
                return false;
            }

            metamethodSet.Add(LuaObjectMetamethod.NewIndex);

            if (!TryEmitMetatable(builder, metamethodSet, context))
            {
                return false;
            }

            builder.AppendLine("}"); // close __Cache

            // Bridging properties so the outer type can access static fields in __Cache
            builder.AppendLine(
                "static global::Lua.LuaFunction __metamethod_index => __Cache.__metamethod_index;"
            );
            builder.AppendLine(
                "static global::Lua.LuaFunction __metamethod_newindex => __Cache.__metamethod_newindex;"
            );

            // Alias properties: __metamethod_foo => __Cache.__function_foo
            // (must come before Metatable, which references them)
            foreach (var alias in tempCollections.AliasProperties)
            {
                builder.AppendLine(
                    $"static global::Lua.LuaFunction {alias.AliasName} => __Cache.{alias.FunctionName};"
                );
            }

            // Static Metatable property (in the outer type, accesses __Cache.__metatable).
            // Use 'new' on interfaces to avoid hiding warning from inherited ILuaUserData.Metatable.
            builder.AppendLine(
                isInterface
                    ? "new static global::Lua.LuaTable? Metatable"
                    : "static global::Lua.LuaTable? Metatable"
            );
            using (builder.BeginBlockScope())
            {
                builder.AppendLine("get");
                using (builder.BeginBlockScope())
                {
                    builder.AppendLine(
                        "if (__Cache.__metatable != null) return __Cache.__metatable;"
                    );
                    builder.AppendLine();
                    builder.AppendLine("__Cache.__metatable = new();");
                    foreach (var metamethod in metamethodSet)
                    {
                        var metaMethodName = metamethod.ToString();
                        var lowerName = metaMethodName.ToLower();
                        builder.AppendLine(
                            $"__Cache.__metatable[global::Lua.Runtime.Metamethods.{metaMethodName}] = __metamethod_{lowerName};"
                        );
                    }
                    builder.AppendLine("return __Cache.__metatable;");
                }

                builder.AppendLine("set");
                using (builder.BeginBlockScope())
                {
                    builder.AppendLine("__Cache.__metatable = value;");
                }
            }

            // ILuaUserData.Metatable implementation.
            // For classes/structs this is an explicit interface implementation.
            // For interfaces this is a default interface implementation (C# 8+ DIM).
            builder.AppendLine(
                "global::Lua.LuaTable? global::Lua.ILuaUserData.Metatable"
            );
            using (builder.BeginBlockScope())
            {
                builder.AppendLine("get => Metatable;");
                builder.AppendLine("set => Metatable = value;");
            }

            // implicit operator (not supported on interfaces)
            if (!isInterface)
            {
                builder.AppendLine(
                    $"public static implicit operator global::Lua.LuaValue({typeMetadata.FullTypeName} value)"
                );
                using (builder.BeginBlockScope())
                {
                    builder.AppendLine("return  global::Lua.LuaValue.FromUserData(value);");
                }
            }

            if (!ns.IsGlobalNamespace)
            {
                builder.EndBlock();
            }

            builder.AppendLine("#pragma warning restore CS0162 // Unreachable code");
            builder.AppendLine(
                "#pragma warning restore CS0219 // Variable assigned but never used"
            );
            builder.AppendLine(
                "#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type."
            );
            builder.AppendLine(
                "#pragma warning restore CS8601 // Possible null reference assignment"
            );
            builder.AppendLine("#pragma warning restore CS8602 // Possible null return");
            builder.AppendLine(
                "#pragma warning restore CS8604 // Possible null reference argument for parameter"
            );
            builder.AppendLine(
                "#pragma warning restore CS8631 // The type cannot be used as type parameter in the generic type or method"
            );
            return true;
        }
        catch (Exception)
        {
            return false;
        }
    }

    static bool ValidateMembers(
        TypeMetadata typeMetadata,
        Compilation compilation,
        SymbolReferences references,
        in SourceProductionContext context,
        Dictionary<INamedTypeSymbol, TypeMetadata> metaDict
    )
    {
        var isValid = true;

        foreach (var property in typeMetadata.Properties)
        {
            if (SymbolEqualityComparer.Default.Equals(property.Type, references.LuaValue))
            {
                continue;
            }

            if (SymbolEqualityComparer.Default.Equals(property.Type, references.LuaUserData))
            {
                continue;
            }

            if (SymbolEqualityComparer.Default.Equals(property.Type, typeMetadata.Symbol))
            {
                continue;
            }

            if (compilation.ClassifyConversion(property.Type, references.LuaUserData).Exists
                || (property.Type is INamedTypeSymbol namedPropType && metaDict.ContainsKey(namedPropType)))
            {
                continue;
            }

            var conversion = compilation.ClassifyConversion(property.Type, references.LuaValue);
            if (
                !conversion.Exists
                && (
                    property.Type is not INamedTypeSymbol namedTypeSymbol
                    || !metaDict.ContainsKey(namedTypeSymbol)
                )
            )
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        DiagnosticDescriptors.InvalidPropertyType,
                        property.Symbol.Locations.FirstOrDefault(),
                        property.Type.Name
                    )
                );

                isValid = false;
            }
        }

        foreach (var method in typeMetadata.Methods)
        {
            if (!method.Symbol.ReturnsVoid)
            {
                var typeSymbol = method.Symbol.ReturnType;

                if (method.IsAsync)
                {
                    var namedType = (INamedTypeSymbol)typeSymbol;
                    if (namedType.TypeArguments.Length == 0)
                    {
                        goto PARAMETERS;
                    }

                    typeSymbol = namedType.TypeArguments[0];
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, references.LuaValue))
                {
                    goto PARAMETERS;
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, references.LuaUserData))
                {
                    goto PARAMETERS;
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, typeMetadata.Symbol))
                {
                    goto PARAMETERS;
                }

                if (compilation.ClassifyConversion(typeSymbol, references.LuaUserData).Exists
                    || (typeSymbol is INamedTypeSymbol namedRetType && metaDict.ContainsKey(namedRetType)))
                {
                    goto PARAMETERS;
                }

                var conversion = compilation.ClassifyConversion(typeSymbol, references.LuaValue);
                if (
                    !conversion.Exists
                    && (
                        typeSymbol is not INamedTypeSymbol namedTypeSymbol
                        || !metaDict.ContainsKey(namedTypeSymbol)
                    )
                )
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DiagnosticDescriptors.InvalidReturnType,
                            typeSymbol.Locations.FirstOrDefault(),
                            typeSymbol.Name
                        )
                    );

                    isValid = false;
                }
            }

            PARAMETERS:
            for (var index = 0; index < method.Symbol.Parameters.Length; index++)
            {
                var parameterSymbol = method.Symbol.Parameters[index];
                var typeSymbol = parameterSymbol.Type;
                if (
                    index == method.Symbol.Parameters.Length - 1
                    && SymbolEqualityComparer.Default.Equals(
                        typeSymbol,
                        references.CancellationToken
                    )
                )
                {
                    continue;
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, references.LuaValue))
                {
                    continue;
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, references.LuaUserData))
                {
                    continue;
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, references.Object))
                {
                    continue;
                }

                if (SymbolEqualityComparer.Default.Equals(typeSymbol, typeMetadata.Symbol))
                {
                    continue;
                }

                if (compilation.ClassifyConversion(typeSymbol, references.LuaUserData).Exists
                    || (typeSymbol is INamedTypeSymbol namedParamType && metaDict.ContainsKey(namedParamType)))
                {
                    continue;
                }

                var conversion = compilation.ClassifyConversion(typeSymbol, references.LuaValue);
                if (
                    !conversion.Exists
                    && (
                        typeSymbol is not INamedTypeSymbol namedTypeSymbol
                        || !metaDict.ContainsKey(namedTypeSymbol)
                    )
                )
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DiagnosticDescriptors.InvalidParameterType,
                            typeSymbol.Locations.FirstOrDefault(),
                            typeSymbol.Name
                        )
                    );

                    isValid = false;
                }
            }
        }

        return isValid;
    }

    static MethodMetadata? GetMetamethod(TypeMetadata typeMetadata, LuaObjectMetamethod metamethod)
    {
        return typeMetadata.Methods.FirstOrDefault(x =>
            x.HasMetamethodAttribute && x.Metamethod == metamethod
        );
    }

    static ITypeSymbol? GetContextArgumentType(
        MethodMetadata methodMetadata,
        int contextArgumentIndex
    )
    {
        var parameterIndex = methodMetadata.IsStatic
            ? contextArgumentIndex
            : contextArgumentIndex - 1;
        if (parameterIndex < 0 || parameterIndex >= methodMetadata.Symbol.Parameters.Length)
        {
            return null;
        }

        return methodMetadata.Symbol.Parameters[parameterIndex].Type;
    }

    static bool IsPreloadableArgumentType(ITypeSymbol? typeSymbol, SymbolReferences references)
    {
        return typeSymbol != null
            && !SymbolEqualityComparer.Default.Equals(typeSymbol, references.LuaValue);
    }

    static void EmitLuaValueCompatibilityCheck(
        CodeBuilder builder,
        string luaValueExpression,
        ITypeSymbol? typeSymbol,
        SymbolReferences references
    )
    {
        if (
            typeSymbol == null
            || SymbolEqualityComparer.Default.Equals(typeSymbol, references.LuaValue)
        )
        {
            builder.Append("true", false);
            return;
        }

        builder.Append(
            $"{luaValueExpression}.TryRead<{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(out _)",
            false
        );
    }

    static bool TryEmitIndexMetamethod(
        TypeMetadata typeMetadata,
        CodeBuilder builder,
        SymbolReferences references,
        Compilation compilation,
        in SourceProductionContext context,
        TempCollections tempCollections
    )
    {
        var customMetamethod = GetMetamethod(typeMetadata, LuaObjectMetamethod.Index);
        var customKeyType =
            customMetamethod == null ? null : GetContextArgumentType(customMetamethod, 1);
        var customHandlesStringKey =
            customMetamethod != null
            && SymbolEqualityComparer.Default.Equals(customKeyType, references.String);

        builder.AppendLine(
            @"internal static readonly global::Lua.LuaFunction __metamethod_index = new global::Lua.LuaFunction(""index"", (context, ct) =>"
        );

        using (builder.BeginBlockScope())
        {
            builder.AppendLine(
                $"var userData = context.GetArgument<{typeMetadata.FullTypeName}>(0);"
            );
            builder.AppendLine("var key = context.GetArgument(1);");
            builder.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (builder.BeginBlockScope())
            {
                foreach (var propertyMetadata in typeMetadata.Properties)
                {
                    if (propertyMetadata.IsWriteOnly)
                    {
                        tempCollections.InvalidMemberNames.Add(propertyMetadata.LuaMemberName);
                        continue;
                    }

                    var conversionPrefix = GetLuaValuePrefix(
                        propertyMetadata.Type,
                        references,
                        compilation
                    );
                    if (propertyMetadata.IsStatic)
                    {
                        builder.AppendLine(
                            @$"if (stringKey == ""{propertyMetadata.LuaMemberName}"") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({conversionPrefix}{typeMetadata.FullTypeName}.{propertyMetadata.Symbol.Name})));"
                        );
                    }
                    else
                    {
                        builder.AppendLine(
                            @$"if (stringKey == ""{propertyMetadata.LuaMemberName}"") return new global::System.Threading.Tasks.ValueTask<int>(context.Return({conversionPrefix}userData.{propertyMetadata.Symbol.Name})));"
                        );
                    }
                }

                foreach (
                    var methodMetadata in typeMetadata.Methods.Where(x => x.HasMemberAttribute)
                )
                {
                    builder.AppendLine(
                        @$"if (stringKey == ""{methodMetadata.LuaMemberName}"") return new global::System.Threading.Tasks.ValueTask<int>(context.Return(new global::Lua.LuaValue(__function_{methodMetadata.LuaMemberName})));"
                    );
                }

                if (tempCollections.InvalidMemberNames.Count > 0)
                {
                    builder.Append("if (stringKey is ", false);
                    for (var index = 0; index < tempCollections.InvalidMemberNames.Count; index++)
                    {
                        var name = tempCollections.InvalidMemberNames[index];
                        builder.Append("\"", false);
                        builder.Append(name, false);
                        builder.Append("\"", false);
                        if (index < tempCollections.InvalidMemberNames.Count - 1)
                        {
                            builder.Append(" or ", false);
                        }
                    }

                    builder.AppendLine(")", false);
                    using (builder.BeginIndentScope())
                    {
                        builder.AppendLine(
                            @"throw new global::Lua.LuaRuntimeException(context.State, $""'{stringKey}' cannot be read."");"
                        );
                    }

                    tempCollections.InvalidMemberNames.Clear();
                }

                if (customMetamethod == null)
                {
                    builder.AppendLine(
                        "return new global::System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));"
                    );
                }
                else if (customHandlesStringKey)
                {
                    using (builder.BeginBlockScope())
                    {
                        EmitMethodFunctionBody(
                            typeMetadata,
                            customMetamethod,
                            builder,
                            references,
                            compilation,
                            new Dictionary<int, string> { [1] = "stringKey" },
                            "userData"
                        );
                    }
                }
            }

            if (customMetamethod != null && !customHandlesStringKey)
            {
                if (IsPreloadableArgumentType(customKeyType, references))
                {
                    builder.Append(@"if (key.TryRead<");
                    builder.Append(
                        customKeyType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        false
                    );
                    builder.AppendLine(@">(out var arg1))", false);
                    using (builder.BeginBlockScope())
                    {
                        EmitMethodFunctionBody(
                            typeMetadata,
                            customMetamethod,
                            builder,
                            references,
                            compilation,
                            new Dictionary<int, string> { [1] = "arg1" },
                            "userData"
                        );
                    }
                }
                else
                {
                    builder.Append("if (");
                    EmitLuaValueCompatibilityCheck(builder, "key", customKeyType, references);
                    builder.AppendLine(")", false);
                    using (builder.BeginBlockScope())
                    {
                        EmitMethodFunctionBody(
                            typeMetadata,
                            customMetamethod,
                            builder,
                            references,
                            compilation,
                            existingUserDataVariable: "userData"
                        );
                    }
                }
            }

            builder.AppendLine(
                "return new global::System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));"
            );
        }

        builder.AppendLine(");");

        return true;
    }

    static bool TryEmitNewIndexMetamethod(
        TypeMetadata typeMetadata,
        CodeBuilder builder,
        SymbolReferences references,
        Compilation compilation,
        in SourceProductionContext context,
        TempCollections tempCollections
    )
    {
        var customMetamethod = GetMetamethod(typeMetadata, LuaObjectMetamethod.NewIndex);
        var customKeyType =
            customMetamethod == null ? null : GetContextArgumentType(customMetamethod, 1);
        var customHandlesStringKey =
            customMetamethod != null
            && SymbolEqualityComparer.Default.Equals(customKeyType, references.String);

        builder.AppendLine(
            @"internal static readonly global::Lua.LuaFunction __metamethod_newindex = new global::Lua.LuaFunction(""newindex"", (context, ct) =>"
        );

        using (builder.BeginBlockScope())
        {
            builder.AppendLine(
                $"var userData = context.GetArgument<{typeMetadata.FullTypeName}>(0);"
            );
            builder.AppendLine("var key = context.GetArgument(1);");
            builder.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (builder.BeginBlockScope())
            {
                foreach (var propertyMetadata in typeMetadata.Properties)
                {
                    // Struct property setters operate on a copy and are silently lost.
                    // For safety, treat all value-type properties as read-only for newindex.
                    if (propertyMetadata.IsReadOnly || typeMetadata.Symbol.IsValueType)
                    {
                        tempCollections.InvalidMemberNames.Add(propertyMetadata.LuaMemberName);
                        continue;
                    }

                    builder.AppendLine(@$"if (stringKey == ""{propertyMetadata.LuaMemberName}"")");
                    using (builder.BeginBlockScope())
                    {
                        if (propertyMetadata.IsStatic)
                        {
                            if (
                                SymbolEqualityComparer.Default.Equals(
                                    propertyMetadata.Type,
                                    references.LuaValue
                                )
                            )
                            {
                                builder.AppendLine(
                                    $"{typeMetadata.FullTypeName}.{propertyMetadata.Symbol.Name} = context.GetArgument(2);"
                                );
                            }
                            else
                            {
                                builder.AppendLine(
                                    $"{typeMetadata.FullTypeName}.{propertyMetadata.Symbol.Name} = context.GetArgument<{propertyMetadata.TypeFullName}>(2);"
                                );
                            }

                            builder.AppendLine(
                                "return new global::System.Threading.Tasks.ValueTask<int>(context.Return());"
                            );
                        }
                        else
                        {
                            if (
                                SymbolEqualityComparer.Default.Equals(
                                    propertyMetadata.Type,
                                    references.LuaValue
                                )
                            )
                            {
                                builder.AppendLine(
                                    $"userData.{propertyMetadata.Symbol.Name} = context.GetArgument(2);"
                                );
                            }
                            else
                            {
                                builder.AppendLine(
                                    $"userData.{propertyMetadata.Symbol.Name} = context.GetArgument<{propertyMetadata.TypeFullName}>(2);"
                                );
                            }

                            builder.AppendLine(
                                "return new global::System.Threading.Tasks.ValueTask<int>(context.Return());"
                            );
                        }
                    }
                }

                foreach (
                    var methodMetadata in typeMetadata.Methods.Where(x => x.HasMemberAttribute)
                )
                {
                    tempCollections.InvalidMemberNames.Add(methodMetadata.LuaMemberName);
                }

                if (tempCollections.InvalidMemberNames.Count > 0)
                {
                    builder.Append("if (stringKey is ");
                    for (var index = 0; index < tempCollections.InvalidMemberNames.Count; index++)
                    {
                        var name = tempCollections.InvalidMemberNames[index];
                        builder.Append("\"", false);
                        builder.Append(name, false);
                        builder.Append("\"", false);
                        if (index < tempCollections.InvalidMemberNames.Count - 1)
                        {
                            builder.Append(" or ", false);
                        }
                    }

                    builder.AppendLine(")");
                    using (builder.BeginBlockScope())
                    {
                        builder.AppendLine(
                            @"throw new global::Lua.LuaRuntimeException(context.State, $""'{stringKey}' cannot overwrite."");"
                        );
                    }

                    tempCollections.InvalidMemberNames.Clear();
                }

                if (customMetamethod == null)
                {
                    builder.AppendLine(
                        @"throw new global::Lua.LuaRuntimeException(context.State, $""'{stringKey}' not found."");"
                    );
                }
                else if (customHandlesStringKey)
                {
                    using (builder.BeginBlockScope())
                    {
                        EmitMethodFunctionBody(
                            typeMetadata,
                            customMetamethod,
                            builder,
                            references,
                            compilation,
                            new Dictionary<int, string> { [1] = "stringKey" },
                            "userData"
                        );
                    }
                }
            }

            if (customMetamethod != null && !customHandlesStringKey)
            {
                if (IsPreloadableArgumentType(customKeyType, references))
                {
                    builder.Append(@"if (key.TryRead<");
                    builder.Append(
                        customKeyType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        false
                    );
                    builder.AppendLine(@">(out var arg1))", false);
                    using (builder.BeginBlockScope())
                    {
                        EmitMethodFunctionBody(
                            typeMetadata,
                            customMetamethod,
                            builder,
                            references,
                            compilation,
                            new Dictionary<int, string> { [1] = "arg1" },
                            "userData"
                        );
                    }
                }
                else
                {
                    builder.Append("if (");
                    EmitLuaValueCompatibilityCheck(builder, "key", customKeyType, references);
                    builder.AppendLine(")", false);
                    using (builder.BeginBlockScope())
                    {
                        EmitMethodFunctionBody(
                            typeMetadata,
                            customMetamethod,
                            builder,
                            references,
                            compilation,
                            existingUserDataVariable: "userData"
                        );
                    }
                }
            }

            builder.AppendLine(
                @"throw new global::Lua.LuaRuntimeException(context.State, $""'{key}' not found."");"
            );
        }

        builder.AppendLine(");");

        return true;
    }

    static bool TryEmitMethods(
        TypeMetadata typeMetadata,
        CodeBuilder builder,
        SymbolReferences references,
        Compilation compilation,
        HashSet<LuaObjectMetamethod> metamethodSet,
        TempCollections tempCollections,
        in SourceProductionContext context
    )
    {
        builder.AppendLine();

        foreach (var methodMetadata in typeMetadata.Methods)
        {
            string? functionName = null;

            if (methodMetadata.HasMemberAttribute)
            {
                functionName = $"__function_{methodMetadata.LuaMemberName}";
                EmitMethodFunction(
                    functionName,
                    methodMetadata.LuaMemberName,
                    typeMetadata,
                    methodMetadata,
                    builder,
                    references,
                    compilation
                );
            }

            if (methodMetadata.HasMetamethodAttribute)
            {
                var metaMethodName = methodMetadata.Metamethod.ToString().ToLower();
                if (!metamethodSet.Add(methodMetadata.Metamethod))
                {
                    // If the duplicate is an auto-detected operator, silently skip
                    // it — explicit [LuaMetamethod] takes precedence.
                    if (methodMetadata.IsAutoDetectedOperator)
                        continue;

                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DiagnosticDescriptors.DuplicateMetamethod,
                            methodMetadata.Symbol.Locations.FirstOrDefault(),
                            typeMetadata.TypeName,
                            metaMethodName
                        )
                    );

                    continue;
                }

                if (functionName == null)
                {
                    if (
                        methodMetadata.Metamethod
                        is not LuaObjectMetamethod.Index
                            and not LuaObjectMetamethod.NewIndex
                    )
                    {
                        var directName = $"__metamethod_{metaMethodName}";
                        EmitMethodFunction(
                            directName,
                            metaMethodName,
                            typeMetadata,
                            methodMetadata,
                            builder,
                            references,
                            compilation
                        );
                        // Add a bridging property so the outer type can reference
                        // this method via the same name (delegates to __Cache).
                        tempCollections.AliasProperties.Add(
                            new()
                            {
                                AliasName = directName,
                                FunctionName = directName
                            }
                        );
                    }
                }
                else if (
                    methodMetadata.Metamethod
                    is not LuaObjectMetamethod.Index
                        and not LuaObjectMetamethod.NewIndex
                )
                {
                    tempCollections.AliasProperties.Add(
                        new()
                        {
                            AliasName = $"__metamethod_{metaMethodName}",
                            FunctionName = functionName
                        }
                    );
                }
            }
        }

        return true;
    }

    static void EmitMethodFunction(
        string functionName,
        string chunkName,
        TypeMetadata typeMetadata,
        MethodMetadata methodMetadata,
        CodeBuilder builder,
        SymbolReferences references,
        Compilation compilation
    )
    {
        builder.AppendLine(
            $@"internal static readonly global::Lua.LuaFunction {functionName} = new global::Lua.LuaFunction(""{chunkName}"", {(methodMetadata.IsAsync ? "async" : "")} (context, ct) =>"
        );

        using (builder.BeginBlockScope())
        {
            EmitMethodFunctionBody(typeMetadata, methodMetadata, builder, references, compilation);
        }

        builder.AppendLine(");");
        builder.AppendLine();
    }

    static void EmitMethodFunctionBody(
        TypeMetadata typeMetadata,
        MethodMetadata methodMetadata,
        CodeBuilder builder,
        SymbolReferences references,
        Compilation compilation,
        IReadOnlyDictionary<int, string>? preloadedArguments = null,
        string? existingUserDataVariable = null
    )
    {
        var index = 0;
        var luaArgumentIndex = 0;
        var callArguments = new List<string>();
        var extraReturnValues = new List<string>();
        var userDataVariable = existingUserDataVariable ?? "userData";

        if (!methodMetadata.IsStatic)
        {
            if (existingUserDataVariable == null)
            {
                builder.AppendLine(
                    $"var {userDataVariable} = context.GetArgument<{typeMetadata.FullTypeName}>(0);"
                );
            }

            index++;
            luaArgumentIndex++;
        }

        var hasCancellationToken = false;

        for (var i = 0; i < methodMetadata.Symbol.Parameters.Length; i++)
        {
            var parameter = methodMetadata.Symbol.Parameters[i];
            var parameterType = parameter.Type;
            var parameterTypeName = parameterType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat
            );
            var variableName = $"arg{index}";
            var isParameterLuaValue = SymbolEqualityComparer.Default.Equals(
                parameterType,
                references.LuaValue
            );

            if (
                i == methodMetadata.Symbol.Parameters.Length - 1
                && SymbolEqualityComparer.Default.Equals(
                    parameterType,
                    references.CancellationToken
                )
            )
            {
                hasCancellationToken = true;
                break;
            }

            if (parameter.RefKind == RefKind.Out)
            {
                builder.AppendLine($"{parameterTypeName} {variableName};");
                callArguments.Add($"out {variableName}");
                extraReturnValues.Add(
                    GetLuaValueExpression(variableName, parameterType, references, compilation)
                );
                index++;
                continue;
            }

            if (
                preloadedArguments != null
                && preloadedArguments.TryGetValue(luaArgumentIndex, out var preloadedArgumentName)
            )
            {
                if (parameter.RefKind == RefKind.Ref)
                {
                    callArguments.Add($"ref {preloadedArgumentName}");
                    extraReturnValues.Add(
                        GetLuaValueExpression(
                            preloadedArgumentName,
                            parameterType,
                            references,
                            compilation
                        )
                    );
                }
                else
                {
                    callArguments.Add(preloadedArgumentName);
                }

                index++;
                luaArgumentIndex++;
                continue;
            }

            if (parameter.HasExplicitDefaultValue)
            {
                var syntax = (ParameterSyntax)parameter.DeclaringSyntaxReferences[0].GetSyntax();

                if (isParameterLuaValue)
                {
                    builder.AppendLine(
                        $"var {variableName} = context.HasArgument({luaArgumentIndex}) ? context.GetArgument({luaArgumentIndex}) : {syntax.Default!.Value.ToFullString()};"
                    );
                }
                else
                {
                    builder.AppendLine(
                        $"var {variableName} = context.HasArgument({luaArgumentIndex}) ? context.GetArgument<{parameterTypeName}>({luaArgumentIndex}) : {syntax.Default!.Value.ToFullString()};"
                    );
                }
            }
            else
            {
                if (isParameterLuaValue)
                {
                    builder.AppendLine(
                        $"var {variableName} = context.GetArgument({luaArgumentIndex});"
                    );
                }
                else
                {
                    builder.AppendLine(
                        $"var {variableName} = context.GetArgument<{parameterTypeName}>({luaArgumentIndex});"
                    );
                }
            }

            if (parameter.RefKind == RefKind.Ref)
            {
                callArguments.Add($"ref {variableName}");
                extraReturnValues.Add(
                    GetLuaValueExpression(variableName, parameterType, references, compilation)
                );
            }
            else
            {
                callArguments.Add(variableName);
            }

            index++;
            luaArgumentIndex++;
        }

        if (methodMetadata.HasReturnValue)
        {
            builder.Append("var result = ");
        }

        if (methodMetadata.IsAsync)
        {
            builder.Append("await ", !methodMetadata.HasReturnValue);
        }

        if (methodMetadata.IsStatic)
        {
            if (methodMetadata.Symbol.MethodKind == MethodKind.UserDefinedOperator
                && TryEmitOperatorCall(methodMetadata, builder, callArguments))
            {
                // Operator expression already emitted by TryEmitOperatorCall.
                builder.AppendLine(";", false);
            }
            else
            {
                builder.Append(
                    $"{typeMetadata.FullTypeName}.{methodMetadata.Symbol.Name}(",
                    !(methodMetadata.HasReturnValue || methodMetadata.IsAsync)
                );
                builder.Append(string.Join(",", callArguments), false);

                if (hasCancellationToken)
                {
                    builder.Append(callArguments.Count > 0 ? ",ct" : "ct", false);
                }

                builder.AppendLine(");", false);
            }
        }
        else
        {
            builder.Append(
                $"{userDataVariable}.{methodMetadata.Symbol.Name}(",
                !(methodMetadata.HasReturnValue || methodMetadata.IsAsync)
            );
            builder.Append(string.Join(",", callArguments), false);

            if (hasCancellationToken)
            {
                builder.Append(callArguments.Count > 0 ? ",ct" : "ct", false);
            }

            builder.AppendLine(");", false);
        }

        var returnValueExpressions = new List<string>();
        if (methodMetadata.HasReturnValue)
        {
            var returnType = methodMetadata.Symbol.ReturnType;
            if (methodMetadata.IsAsync)
            {
                var namedType = (INamedTypeSymbol)returnType;
                if (namedType.TypeArguments.Length == 1)
                {
                    returnType = namedType.TypeArguments[0];
                }
            }

            returnValueExpressions.Add(
                GetLuaValueExpression("result", returnType, references, compilation)
            );
        }

        returnValueExpressions.AddRange(extraReturnValues);

        switch (returnValueExpressions.Count)
        {
            case 0:
                builder.AppendLine(
                    methodMetadata.IsAsync
                        ? "return context.Return();"
                        : "return new global::System.Threading.Tasks.ValueTask<int>(context.Return());"
                );
                break;
            case 1:
                builder.AppendLine(
                    methodMetadata.IsAsync
                        ? $"return context.Return({returnValueExpressions[0]});"
                        : $"return new global::System.Threading.Tasks.ValueTask<int>(context.Return({returnValueExpressions[0]}));"
                );
                break;
            case 2:
                builder.AppendLine(
                    methodMetadata.IsAsync
                        ? $"return context.Return({returnValueExpressions[0]}, {returnValueExpressions[1]});"
                        : $"return new global::System.Threading.Tasks.ValueTask<int>(context.Return({returnValueExpressions[0]}, {returnValueExpressions[1]}));"
                );
                break;
            case 3:
                builder.AppendLine(
                    methodMetadata.IsAsync
                        ? $"return context.Return({returnValueExpressions[0]}, {returnValueExpressions[1]}, {returnValueExpressions[2]});"
                        : $"return new global::System.Threading.Tasks.ValueTask<int>(context.Return({returnValueExpressions[0]}, {returnValueExpressions[1]}, {returnValueExpressions[2]}));"
                );
                break;
            default:
                builder.AppendLine(
                    $"var __returnValues = context.GetReturnBuffer({returnValueExpressions.Count});"
                );
                for (var i = 0; i < returnValueExpressions.Count; i++)
                {
                    builder.AppendLine($"__returnValues[{i}] = {returnValueExpressions[i]};");
                }

                builder.AppendLine(
                    methodMetadata.IsAsync
                        ? $"return {returnValueExpressions.Count};"
                        : $"return new global::System.Threading.Tasks.ValueTask<int>({returnValueExpressions.Count});"
                );

                break;
        }

    /// <summary>
    /// Returns the C# operator symbol for the given method name, or null if it
    /// is not a supported user-defined operator.
    /// </summary>
    static string? GetOperatorSymbol(string methodName, int parameterCount)
    {
        return methodName switch
        {
            "op_Addition" => "+",
            "op_Subtraction" when parameterCount == 2 => "-",
            "op_Subtraction" when parameterCount == 1 => "-",
            "op_Multiply" => "*",
            "op_Division" => "/",
            "op_Modulus" => "%",
            "op_UnaryNegation" => "-",
            "op_Equality" => "==",
            "op_LessThan" => "<",
            "op_LessThanOrEqual" => "<=",
            _ => null,
        };
    }

    /// <summary>
    /// Emits a C# operator invocation expression (e.g. "(arg0 + arg1)").
    /// Returns true if the method was a supported operator; false otherwise.
    /// </summary>
    static bool TryEmitOperatorCall(
        MethodMetadata methodMetadata,
        CodeBuilder builder,
        List<string> callArguments)
    {
        var op = GetOperatorSymbol(methodMetadata.Symbol.Name, methodMetadata.Symbol.Parameters.Length);
        if (op == null)
            return false;

        var isUnary = methodMetadata.Symbol.Parameters.Length == 1;
        builder.Append("(", false);
        if (isUnary)
        {
            builder.Append(op, false);
            builder.Append(callArguments[0], false);
        }
        else
        {
            builder.Append(callArguments[0], false);
            builder.Append(" " + op + " ", false);
            builder.Append(callArguments[1], false);
        }
        builder.Append(")", false);
        return true;
    }
    }

    static bool TryEmitMetatable(
        CodeBuilder builder,
        IEnumerable<LuaObjectMetamethod> metamethods,
        in SourceProductionContext context
    )
    {
        // The backing field lives inside __Cache.
        // The static Metatable property (and ILuaUserData.Metatable) are emitted
        // by TryEmit after the cache is closed, so they live in the outer type.
        builder.AppendLine("internal static global::Lua.LuaTable? __metatable;");
        builder.AppendLine();

        return true;
    }
}
